import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
// import Image from "next/image";
// import Link from "next/link";

import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
// import { SessionProvider } from "next-auth/react";
import NextAuthProvider from "@/provider/NextAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Foodian",
  description: "Generated by create next app",
};

import { Toaster } from "react-hot-toast";

export default function RootLayout({ children }) {
  return (

    <NextAuthProvider>
      <html lang="en">
        <body
          // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          className={`${poppins.className} antialiased`}
        >
          <Header></Header>
          <main className="py-8">
            {children}
          </main>
          <Footer></Footer>
          <Toaster position="top-center" />
        </body>
      </html>
    </NextAuthProvider>
  );
}
