import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Image from "next/image";
// import Link from "next/link";

import Header from "@/Components/Header";
import Footer from "@/Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Foodian",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header></Header>
         <main className="px-5 py-8">
          {children}
         </main>
         <Footer></Footer>
        
      </body>
    </html>
  );
}
